services:
  web:
    build: .
    ports:
      - "8000:8000"            
    env_file:
      - .env                   
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    command: >
      gunicorn -w 2 -k gthread -b 0.0.0.0:8000 main:app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; sys.exit(0) if urllib.request.urlopen('http://127.0.0.1:8000/healthz').status==200 else sys.exit(1)"]
      interval: 30s
      timeout: 3s
      retries: 3
